// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steelcerts/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetCertificateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCertificateRequest) Reset()         { *m = QueryGetCertificateRequest{} }
func (m *QueryGetCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCertificateRequest) ProtoMessage()    {}
func (*QueryGetCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6276f13c96e12d11, []int{0}
}
func (m *QueryGetCertificateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCertificateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCertificateRequest.Merge(m, src)
}
func (m *QueryGetCertificateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCertificateRequest proto.InternalMessageInfo

func (m *QueryGetCertificateRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCertificateResponse struct {
	Certificate Certificate `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate"`
}

func (m *QueryGetCertificateResponse) Reset()         { *m = QueryGetCertificateResponse{} }
func (m *QueryGetCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCertificateResponse) ProtoMessage()    {}
func (*QueryGetCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6276f13c96e12d11, []int{1}
}
func (m *QueryGetCertificateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCertificateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCertificateResponse.Merge(m, src)
}
func (m *QueryGetCertificateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCertificateResponse proto.InternalMessageInfo

func (m *QueryGetCertificateResponse) GetCertificate() Certificate {
	if m != nil {
		return m.Certificate
	}
	return Certificate{}
}

type QueryAllCertificateRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCertificateRequest) Reset()         { *m = QueryAllCertificateRequest{} }
func (m *QueryAllCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCertificateRequest) ProtoMessage()    {}
func (*QueryAllCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6276f13c96e12d11, []int{2}
}
func (m *QueryAllCertificateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCertificateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCertificateRequest.Merge(m, src)
}
func (m *QueryAllCertificateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCertificateRequest proto.InternalMessageInfo

func (m *QueryAllCertificateRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCertificateResponse struct {
	Certificate []Certificate       `protobuf:"bytes,1,rep,name=certificate,proto3" json:"certificate"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCertificateResponse) Reset()         { *m = QueryAllCertificateResponse{} }
func (m *QueryAllCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCertificateResponse) ProtoMessage()    {}
func (*QueryAllCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6276f13c96e12d11, []int{3}
}
func (m *QueryAllCertificateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCertificateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCertificateResponse.Merge(m, src)
}
func (m *QueryAllCertificateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCertificateResponse proto.InternalMessageInfo

func (m *QueryAllCertificateResponse) GetCertificate() []Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *QueryAllCertificateResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCertificateRequest)(nil), "sapcis.steelcerts.steelcerts.QueryGetCertificateRequest")
	proto.RegisterType((*QueryGetCertificateResponse)(nil), "sapcis.steelcerts.steelcerts.QueryGetCertificateResponse")
	proto.RegisterType((*QueryAllCertificateRequest)(nil), "sapcis.steelcerts.steelcerts.QueryAllCertificateRequest")
	proto.RegisterType((*QueryAllCertificateResponse)(nil), "sapcis.steelcerts.steelcerts.QueryAllCertificateResponse")
}

func init() { proto.RegisterFile("steelcerts/query.proto", fileDescriptor_6276f13c96e12d11) }

var fileDescriptor_6276f13c96e12d11 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0xae, 0x12, 0x31,
	0x14, 0x9d, 0x82, 0x98, 0x58, 0x12, 0x17, 0x0d, 0x31, 0x66, 0x24, 0xa3, 0x99, 0x85, 0x8a, 0x26,
	0x6d, 0x06, 0x36, 0xb2, 0x04, 0x13, 0x89, 0x3b, 0x99, 0xa5, 0xbb, 0xce, 0x50, 0xc7, 0x26, 0xc3,
	0x74, 0xa0, 0xc5, 0x40, 0x8c, 0x1b, 0xbe, 0xc0, 0xc4, 0x9f, 0xd1, 0x85, 0x7b, 0x96, 0x24, 0x6e,
	0x5c, 0x19, 0x03, 0x7e, 0x88, 0x99, 0x76, 0x5e, 0xe8, 0x7b, 0x19, 0x78, 0xe4, 0xbd, 0x0d, 0xb9,
	0xa5, 0x3d, 0xe7, 0x9e, 0x73, 0xee, 0x1d, 0xf8, 0x40, 0x2a, 0xc6, 0xd2, 0x98, 0xcd, 0x95, 0x24,
	0xb3, 0x05, 0x9b, 0xaf, 0x70, 0x3e, 0x17, 0x4a, 0xa0, 0xb6, 0xa4, 0x79, 0xcc, 0x25, 0x3e, 0x5c,
	0x5b, 0xa5, 0xdb, 0x4e, 0x84, 0x48, 0x52, 0x46, 0x68, 0xce, 0x09, 0xcd, 0x32, 0xa1, 0xa8, 0xe2,
	0x22, 0x93, 0x06, 0xeb, 0xbe, 0x88, 0x85, 0x9c, 0x0a, 0x49, 0x22, 0x2a, 0x99, 0x21, 0x25, 0x9f,
	0x82, 0x88, 0x29, 0x1a, 0x90, 0x9c, 0x26, 0x3c, 0xd3, 0x8f, 0xcb, 0xb7, 0x6d, 0xab, 0x7f, 0xf1,
	0xcb, 0x3f, 0xf0, 0x98, 0x2a, 0x56, 0xde, 0xb6, 0x12, 0x91, 0x08, 0x5d, 0x92, 0xa2, 0x32, 0xff,
	0xfa, 0x5d, 0xe8, 0x8e, 0x0b, 0xd6, 0x11, 0x53, 0xaf, 0x0f, 0x90, 0x90, 0xcd, 0x16, 0x4c, 0x2a,
	0xd4, 0x82, 0x0d, 0x9e, 0x4d, 0xd8, 0xf2, 0x21, 0x78, 0x02, 0x9e, 0xdf, 0x0b, 0xcd, 0xc1, 0xcf,
	0xe1, 0xa3, 0x4a, 0x8c, 0xcc, 0x45, 0x26, 0x19, 0x1a, 0xc3, 0xa6, 0xd5, 0x5d, 0x43, 0x9b, 0xdd,
	0x0e, 0x3e, 0x15, 0x02, 0xb6, 0x78, 0x86, 0x77, 0x36, 0x7f, 0x1e, 0x3b, 0xa1, 0xcd, 0xe1, 0x4f,
	0x4a, 0x95, 0x83, 0x34, 0xad, 0x50, 0xf9, 0x06, 0xc2, 0x43, 0x16, 0x65, 0xbf, 0xa7, 0xd8, 0x04,
	0x87, 0x8b, 0xe0, 0xb0, 0x99, 0x46, 0x19, 0x1c, 0x7e, 0x47, 0x93, 0x0b, 0x6c, 0x68, 0x21, 0xfd,
	0x1f, 0xa0, 0x34, 0x76, 0xb5, 0xcd, 0x31, 0x63, 0xf5, 0xdb, 0x1a, 0x43, 0xa3, 0x4b, 0xd2, 0x6b,
	0x5a, 0xfa, 0xb3, 0x6b, 0xa5, 0x1b, 0x3d, 0xb6, 0xf6, 0xee, 0xba, 0x0e, 0x1b, 0x5a, 0x3b, 0xfa,
	0x09, 0x60, 0xd3, 0xea, 0x8a, 0x5e, 0x9d, 0x16, 0x78, 0x7c, 0xfa, 0x6e, 0xff, 0x06, 0x48, 0x23,
	0xcd, 0xef, 0xaf, 0x7f, 0xfd, 0xfb, 0x56, 0xeb, 0xa1, 0x80, 0x18, 0x0a, 0x62, 0xad, 0x66, 0xf5,
	0x96, 0x92, 0xcf, 0x7a, 0xb9, 0xbe, 0xa0, 0xef, 0x00, 0xde, 0xb7, 0x28, 0x07, 0x69, 0x7a, 0x96,
	0x85, 0xca, 0xd5, 0x38, 0xcb, 0x42, 0xf5, 0xb4, 0xfd, 0x40, 0x5b, 0x78, 0x89, 0x3a, 0x67, 0x5b,
	0x18, 0xbe, 0xdd, 0xec, 0x3c, 0xb0, 0xdd, 0x79, 0xe0, 0xef, 0xce, 0x03, 0x5f, 0xf7, 0x9e, 0xb3,
	0xdd, 0x7b, 0xce, 0xef, 0xbd, 0xe7, 0xbc, 0x27, 0x09, 0x57, 0x1f, 0x17, 0x11, 0x8e, 0xc5, 0xb4,
	0x82, 0x6e, 0x69, 0x1f, 0xd4, 0x2a, 0x67, 0x32, 0xba, 0xab, 0x3f, 0xcf, 0xde, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x87, 0xfe, 0x68, 0x54, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a certificate by index.
	Certificate(ctx context.Context, in *QueryGetCertificateRequest, opts ...grpc.CallOption) (*QueryGetCertificateResponse, error)
	// Queries a list of certificate items.
	CertificateAll(ctx context.Context, in *QueryAllCertificateRequest, opts ...grpc.CallOption) (*QueryAllCertificateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Certificate(ctx context.Context, in *QueryGetCertificateRequest, opts ...grpc.CallOption) (*QueryGetCertificateResponse, error) {
	out := new(QueryGetCertificateResponse)
	err := c.cc.Invoke(ctx, "/sapcis.steelcerts.steelcerts.Query/Certificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CertificateAll(ctx context.Context, in *QueryAllCertificateRequest, opts ...grpc.CallOption) (*QueryAllCertificateResponse, error) {
	out := new(QueryAllCertificateResponse)
	err := c.cc.Invoke(ctx, "/sapcis.steelcerts.steelcerts.Query/CertificateAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a certificate by index.
	Certificate(context.Context, *QueryGetCertificateRequest) (*QueryGetCertificateResponse, error)
	// Queries a list of certificate items.
	CertificateAll(context.Context, *QueryAllCertificateRequest) (*QueryAllCertificateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Certificate(ctx context.Context, req *QueryGetCertificateRequest) (*QueryGetCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Certificate not implemented")
}
func (*UnimplementedQueryServer) CertificateAll(ctx context.Context, req *QueryAllCertificateRequest) (*QueryAllCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertificateAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Certificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Certificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sapcis.steelcerts.steelcerts.Query/Certificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Certificate(ctx, req.(*QueryGetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CertificateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CertificateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sapcis.steelcerts.steelcerts.Query/CertificateAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CertificateAll(ctx, req.(*QueryAllCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sapcis.steelcerts.steelcerts.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Certificate",
			Handler:    _Query_Certificate_Handler,
		},
		{
			MethodName: "CertificateAll",
			Handler:    _Query_CertificateAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steelcerts/query.proto",
}

func (m *QueryGetCertificateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCertificateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCertificateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCertificateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCertificateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCertificateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Certificate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCertificateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCertificateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCertificateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCertificateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCertificateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCertificateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Certificate) > 0 {
		for iNdEx := len(m.Certificate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Certificate[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCertificateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCertificateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Certificate.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCertificateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCertificateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Certificate) > 0 {
		for _, e := range m.Certificate {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCertificateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCertificateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCertificateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCertificateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCertificateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCertificateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Certificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCertificateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCertificateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCertificateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCertificateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCertificateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCertificateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificate = append(m.Certificate, Certificate{})
			if err := m.Certificate[len(m.Certificate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
